/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LedigeBoligerRouteImport } from './routes/ledige-boliger'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LedigeBoligerIdRouteImport } from './routes/ledige-boliger.$id'

const LedigeBoligerRoute = LedigeBoligerRouteImport.update({
  id: '/ledige-boliger',
  path: '/ledige-boliger',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LedigeBoligerIdRoute = LedigeBoligerIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LedigeBoligerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ledige-boliger': typeof LedigeBoligerRouteWithChildren
  '/ledige-boliger/$id': typeof LedigeBoligerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ledige-boliger': typeof LedigeBoligerRouteWithChildren
  '/ledige-boliger/$id': typeof LedigeBoligerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ledige-boliger': typeof LedigeBoligerRouteWithChildren
  '/ledige-boliger/$id': typeof LedigeBoligerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ledige-boliger' | '/ledige-boliger/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ledige-boliger' | '/ledige-boliger/$id'
  id: '__root__' | '/' | '/ledige-boliger' | '/ledige-boliger/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LedigeBoligerRoute: typeof LedigeBoligerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ledige-boliger': {
      id: '/ledige-boliger'
      path: '/ledige-boliger'
      fullPath: '/ledige-boliger'
      preLoaderRoute: typeof LedigeBoligerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledige-boliger/$id': {
      id: '/ledige-boliger/$id'
      path: '/$id'
      fullPath: '/ledige-boliger/$id'
      preLoaderRoute: typeof LedigeBoligerIdRouteImport
      parentRoute: typeof LedigeBoligerRoute
    }
  }
}

interface LedigeBoligerRouteChildren {
  LedigeBoligerIdRoute: typeof LedigeBoligerIdRoute
}

const LedigeBoligerRouteChildren: LedigeBoligerRouteChildren = {
  LedigeBoligerIdRoute: LedigeBoligerIdRoute,
}

const LedigeBoligerRouteWithChildren = LedigeBoligerRoute._addFileChildren(
  LedigeBoligerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LedigeBoligerRoute: LedigeBoligerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
