/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LedigeBoligerIndexRouteImport } from './routes/ledige-boliger.index'
import { Route as LedigeBoligerIdRouteImport } from './routes/ledige-boliger.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LedigeBoligerIndexRoute = LedigeBoligerIndexRouteImport.update({
  id: '/ledige-boliger/',
  path: '/ledige-boliger/',
  getParentRoute: () => rootRouteImport,
} as any)
const LedigeBoligerIdRoute = LedigeBoligerIdRouteImport.update({
  id: '/ledige-boliger/$id',
  path: '/ledige-boliger/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ledige-boliger/$id': typeof LedigeBoligerIdRoute
  '/ledige-boliger/': typeof LedigeBoligerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ledige-boliger/$id': typeof LedigeBoligerIdRoute
  '/ledige-boliger': typeof LedigeBoligerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ledige-boliger/$id': typeof LedigeBoligerIdRoute
  '/ledige-boliger/': typeof LedigeBoligerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ledige-boliger/$id' | '/ledige-boliger/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ledige-boliger/$id' | '/ledige-boliger'
  id: '__root__' | '/' | '/ledige-boliger/$id' | '/ledige-boliger/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LedigeBoligerIdRoute: typeof LedigeBoligerIdRoute
  LedigeBoligerIndexRoute: typeof LedigeBoligerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledige-boliger/': {
      id: '/ledige-boliger/'
      path: '/ledige-boliger'
      fullPath: '/ledige-boliger/'
      preLoaderRoute: typeof LedigeBoligerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledige-boliger/$id': {
      id: '/ledige-boliger/$id'
      path: '/ledige-boliger/$id'
      fullPath: '/ledige-boliger/$id'
      preLoaderRoute: typeof LedigeBoligerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LedigeBoligerIdRoute: LedigeBoligerIdRoute,
  LedigeBoligerIndexRoute: LedigeBoligerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
